[features]
seeds = false
skip-lint = false

[programs.localnet]
bridge = "4LN58RWxhbQgsAMVpi6bgrJgmY6rvLdohZpBNenFPY27"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mori/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
